import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../_Components/Header";
import Footer from "../_Components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute :"",
    default :"Home | ShopMe",
    template :" %s | ShopMe",  
  } ,
  description: "Generated by JuGurta Hadjam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width"/>
        <link rel="icon" href="/favicon.svg" type="image/x-icon" sizes="32x32"/>
      </head>
      <body className={inter.className}>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
